#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class ComboBox;
                ref class CalendarDatePicker;
                ref class TimePicker;
                ref class ToggleSwitch;
                ref class AppBarButton;
            }
        }
    }
}

namespace CheckoutManager
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class AddCheckout : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        void UnloadObject(::Windows::UI::Xaml::DependencyObject^ dependencyObject);
        void DisconnectUnloadedObject(int connectionId);
    
    private:
        bool _contentLoaded;
    
    
        private: ::Windows::UI::Xaml::Controls::ComboBox^ teamSelector;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ devicepicker;
        private: ::Windows::UI::Xaml::Controls::CalendarDatePicker^ returnDate;
        private: ::Windows::UI::Xaml::Controls::TimePicker^ returnTime;
        private: ::Windows::UI::Xaml::Controls::CalendarDatePicker^ startDate;
        private: ::Windows::UI::Xaml::Controls::TimePicker^ startTime;
        private: ::Windows::UI::Xaml::Controls::ToggleSwitch^ sameDay;
        private: ::Windows::UI::Xaml::Controls::AppBarButton^ savebutton;
        private: ::Windows::UI::Xaml::Controls::AppBarButton^ deleteButton;
        private: ::Windows::UI::Xaml::Controls::AppBarButton^ CloseButton;
    };
}

