//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#pragma warning(push)
#pragma warning(disable: 4100) // unreferenced formal parameter

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "AddCheckout.xaml.h"

void ::CheckoutManager::AddCheckout::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///AddCheckout.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::CheckoutManager::AddCheckout::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
    case 2:
        {
            this->teamSelector = safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(this->teamSelector))->SelectionChanged += ref new ::Windows::UI::Xaml::Controls::SelectionChangedEventHandler(this, (void (::CheckoutManager::AddCheckout::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Controls::SelectionChangedEventArgs^))&AddCheckout::teamSelector_SelectionChanged);
        }
        break;
    case 3:
        {
            this->devicepicker = safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(this->devicepicker))->SelectionChanged += ref new ::Windows::UI::Xaml::Controls::SelectionChangedEventHandler(this, (void (::CheckoutManager::AddCheckout::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Controls::SelectionChangedEventArgs^))&AddCheckout::teamSelector_SelectionChanged);
        }
        break;
    case 4:
        {
            this->returnDate = safe_cast<::Windows::UI::Xaml::Controls::CalendarDatePicker^>(__target);
        }
        break;
    case 5:
        {
            this->returnTime = safe_cast<::Windows::UI::Xaml::Controls::TimePicker^>(__target);
        }
        break;
    case 6:
        {
            this->startDate = safe_cast<::Windows::UI::Xaml::Controls::CalendarDatePicker^>(__target);
        }
        break;
    case 7:
        {
            this->startTime = safe_cast<::Windows::UI::Xaml::Controls::TimePicker^>(__target);
        }
        break;
    case 8:
        {
            this->sameDay = safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(this->sameDay))->Toggled += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::CheckoutManager::AddCheckout::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&AddCheckout::sameDay_Toggled);
        }
        break;
    case 9:
        {
            this->savebutton = safe_cast<::Windows::UI::Xaml::Controls::AppBarButton^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::AppBarButton^>(this->savebutton))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::CheckoutManager::AddCheckout::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&AddCheckout::AppBarButton_Click);
        }
        break;
    case 10:
        {
            this->deleteButton = safe_cast<::Windows::UI::Xaml::Controls::AppBarButton^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::AppBarButton^>(this->deleteButton))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::CheckoutManager::AddCheckout::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&AddCheckout::deleteButton_Click);
        }
        break;
    case 11:
        {
            this->CloseButton = safe_cast<::Windows::UI::Xaml::Controls::AppBarButton^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::AppBarButton^>(this->CloseButton))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::CheckoutManager::AddCheckout::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&AddCheckout::CloseButton_Click);
        }
        break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::CheckoutManager::AddCheckout::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}

#pragma warning(pop)


