#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class ComboBox;
                ref class PasswordBox;
                ref class TextBlock;
                ref class Button;
                ref class SymbolIcon;
            }
        }
    }
}

namespace CheckoutManager
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class AuthenticationDialog : public ::Windows::UI::Xaml::Controls::ContentDialog, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        void UnloadObject(::Windows::UI::Xaml::DependencyObject^ dependencyObject);
        void DisconnectUnloadedObject(int connectionId);
    
    private:
        bool _contentLoaded;
    
    
        private: ::Windows::UI::Xaml::Controls::ComboBox^ user;
        private: ::Windows::UI::Xaml::Controls::PasswordBox^ passbox;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ passWarning;
        private: ::Windows::UI::Xaml::Controls::Button^ loginbutton;
        private: ::Windows::UI::Xaml::Controls::SymbolIcon^ logIndicator;
    };
}

