//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#pragma warning(push)
#pragma warning(disable: 4100) // unreferenced formal parameter

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "CheckoutPage.xaml.h"

void ::CheckoutManager::CheckoutPage::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///CheckoutPage.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::CheckoutManager::CheckoutPage::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
    case 1:
        {
            this->IDbox = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
        }
        break;
    case 2:
        {
            this->teamSelector = safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(this->teamSelector))->SelectionChanged += ref new ::Windows::UI::Xaml::Controls::SelectionChangedEventHandler(this, (void (::CheckoutManager::CheckoutPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Controls::SelectionChangedEventArgs^))&CheckoutPage::teamSelector_SelectionChanged);
        }
        break;
    case 3:
        {
            this->password = safe_cast<::Windows::UI::Xaml::Controls::PasswordBox^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::PasswordBox^>(this->password))->PasswordChanged += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::CheckoutManager::CheckoutPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&CheckoutPage::PasswordBox_PasswordChanged);
        }
        break;
    case 4:
        {
            this->checkoutbutton = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->checkoutbutton))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::CheckoutManager::CheckoutPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&CheckoutPage::Button_Click);
        }
        break;
    case 5:
        {
            this->warning = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 6:
        {
            this->statusBlock = safe_cast<::Windows::UI::Xaml::Controls::RichTextBlock^>(__target);
        }
        break;
    case 7:
        {
            this->devTypeblock = safe_cast<::Windows::UI::Xaml::Documents::Run^>(__target);
        }
        break;
    case 8:
        {
            this->IDblock = safe_cast<::Windows::UI::Xaml::Documents::Run^>(__target);
        }
        break;
    case 9:
        {
            this->userblock = safe_cast<::Windows::UI::Xaml::Documents::Run^>(__target);
        }
        break;
    case 10:
        {
            this->dueblock = safe_cast<::Windows::UI::Xaml::Documents::Run^>(__target);
        }
        break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::CheckoutManager::CheckoutPage::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}

#pragma warning(pop)


