#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

#include "XamlBindingInfo.g.h"

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Grid;
                ref class ListView;
                ref class TextBox;
                ref class Button;
                ref class TextBlock;
                ref class ComboBox;
                ref class PasswordBox;
                ref class RichTextBlock;
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Documents {
                ref class Run;
            }
        }
    }
}

namespace CheckoutManager
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class CheckoutPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        void UnloadObject(::Windows::UI::Xaml::DependencyObject^ dependencyObject);
        void DisconnectUnloadedObject(int connectionId);
    
    private:
        bool _contentLoaded;
    
        class CheckoutPage_obj4_Bindings;
        class CheckoutPage_obj11_Bindings;
    
        ::XamlBindingInfo::XamlBindings^ Bindings;
        private: ::Windows::UI::Xaml::Controls::Grid^ CheckoutPanel;
        private: ::Windows::UI::Xaml::Controls::ListView^ overdueview;
        private: ::Windows::UI::Xaml::Controls::ListView^ currentListview;
        private: ::Windows::UI::Xaml::Controls::TextBox^ returnBox;
        private: ::Windows::UI::Xaml::Controls::Button^ Returnbutton;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ returnBlock;
        private: ::Windows::UI::Xaml::Controls::TextBox^ IDbox;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ teamSelector;
        private: ::Windows::UI::Xaml::Controls::PasswordBox^ password;
        private: ::Windows::UI::Xaml::Controls::Button^ checkoutbutton;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ warning;
        private: ::Windows::UI::Xaml::Controls::RichTextBlock^ statusBlock;
        private: ::Windows::UI::Xaml::Documents::Run^ devTypeblock;
        private: ::Windows::UI::Xaml::Documents::Run^ IDblock;
        private: ::Windows::UI::Xaml::Documents::Run^ userblock;
        private: ::Windows::UI::Xaml::Documents::Run^ dueblock;
    };
}

