//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#pragma warning(push)
#pragma warning(disable: 4100) // unreferenced formal parameter

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "DeviceViewPage.xaml.h"

void ::CheckoutManager::DeviceViewPage::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///DeviceViewPage.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}


/// <summary>
/// Auto generated class for compiled bindings.
/// </summary>
class CheckoutManager::DeviceViewPage::DeviceViewPage_obj3_Bindings 
    : public ::XamlBindingInfo::ValueTypeXamlBindings<::CheckoutManager::device, ::XamlBindingInfo::XamlBindingTrackingBase>
{
            ::Windows::UI::Xaml::ResourceDictionary^ localResources;
            ::Platform::WeakReference converterLookupRoot;
public:
    DeviceViewPage_obj3_Bindings()
    {
    }

    void Connect(int __connectionId, ::Platform::Object^ __target)
    {
        switch(__connectionId)
        {
            case 3: // DeviceViewPage.xaml line 18
                this->obj3 = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
                break;
            case 4: // DeviceViewPage.xaml line 21
                this->obj4 = safe_cast<::Windows::UI::Xaml::Controls::MenuFlyoutItem^>(__target);
                break;
            case 5: // DeviceViewPage.xaml line 36
                this->obj5 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
                break;
            case 6: // DeviceViewPage.xaml line 33
                this->obj6 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
                break;
            case 7: // DeviceViewPage.xaml line 30
                this->obj7 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
                break;
        }
    }

    void DisconnectUnloadedObject(int connectionId)
    {
        throw ref new ::Platform::InvalidArgumentException("No unloadable elements to disconnect.");
    }

    void Recycle()
    {
    }

    void ProcessBindings(::Platform::Object^ item, int itemIndex, int phase, int* nextPhase)
    {
        switch (phase)
        {
            case 0:
                *nextPhase = -1;
                this->SetDataRoot(static_cast<::CheckoutManager::device>(item));
                if (this->_dataContextChangedToken.Value != 0)
                {
                    this->obj3.Resolve<::Windows::UI::Xaml::Controls::Grid>()->DataContextChanged -= this->_dataContextChangedToken;
                    this->_dataContextChangedToken.Value = 0;
                }
                this->_isInitialized = true;
                break;
            default:
                *nextPhase = -1;
                break;
        }
        this->Update_((::CheckoutManager::device) item, 1 << phase);
    }

    void SetConverterLookupRoot(::Windows::UI::Xaml::FrameworkElement^ rootElement)
    {
        this->converterLookupRoot = rootElement;
    }

    ::Windows::UI::Xaml::Data::IValueConverter^ LookupConverter(::Platform::String^ key)
    {
        if (this->localResources == nullptr)
        {
            this->localResources = this->converterLookupRoot.Resolve<::Windows::UI::Xaml::FrameworkElement>()->Resources;
            this->converterLookupRoot = nullptr;
            }
        return safe_cast<::Windows::UI::Xaml::Data::IValueConverter^>(this->localResources->HasKey(key) ? this->localResources->Lookup(key) : ::Windows::UI::Xaml::Application::Current->Resources->Lookup(key));
    }

private:
    // Fields for each control that has bindings.
    ::Platform::WeakReference obj3;
    ::Windows::UI::Xaml::Controls::MenuFlyoutItem^ obj4;
    ::Windows::UI::Xaml::Controls::TextBlock^ obj5;
    ::Windows::UI::Xaml::Controls::TextBlock^ obj6;
    ::Windows::UI::Xaml::Controls::TextBlock^ obj7;

    // Update methods for each path node used in binding steps.
    void Update_(::CheckoutManager::device obj, int phase)
    {
            if ((phase & (NOT_PHASED | (1 << 0))) != 0)
            {
                this->Update_checkedOut(obj.checkedOut, phase);
                this->Update_deviceID(obj.deviceID, phase);
                this->Update_currentRentee(obj.currentRentee, phase);
                this->Update_description(obj.description, phase);
            }
    }
    void Update_checkedOut(::Platform::Boolean obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // DeviceViewPage.xaml line 18
            if (this->obj3 != nullptr)
            {
                Set_Windows_UI_Xaml_Controls_Panel_Background(this->obj3.Resolve<::Windows::UI::Xaml::Controls::Grid>(), safe_cast<::Windows::UI::Xaml::Media::Brush^>(this->LookupConverter("availconverter")->Convert(obj, ::Windows::UI::Xaml::Media::Brush::typeid, "str", nullptr)), nullptr);
            }
        }
    }
    void Update_deviceID(::default::int32 obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // DeviceViewPage.xaml line 21
            Set_Windows_UI_Xaml_FrameworkElement_Tag(this->obj4, obj, nullptr);
            // DeviceViewPage.xaml line 36
            Set_Windows_UI_Xaml_Controls_TextBlock_Text(this->obj5, obj.ToString(), nullptr);
        }
    }
    void Update_currentRentee(::Platform::String^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // DeviceViewPage.xaml line 33
            Set_Windows_UI_Xaml_Controls_TextBlock_Text(this->obj6, obj, nullptr);
        }
    }
    void Update_description(::Platform::String^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // DeviceViewPage.xaml line 30
            Set_Windows_UI_Xaml_Controls_TextBlock_Text(this->obj7, obj, nullptr);
        }
    }
    static void Set_Windows_UI_Xaml_Controls_Panel_Background(::Windows::UI::Xaml::Controls::Panel^ obj, ::Windows::UI::Xaml::Media::Brush^ value, ::Platform::String^ targetNullValue)
    {
        if (value == nullptr && targetNullValue != nullptr)
        {
            value = (::Windows::UI::Xaml::Media::Brush^) ::Windows::UI::Xaml::Markup::XamlBindingHelper::ConvertValue(::Windows::UI::Xaml::Media::Brush::typeid, targetNullValue);
        }
        obj->Background = value;
    }
    static void Set_Windows_UI_Xaml_FrameworkElement_Tag(::Windows::UI::Xaml::FrameworkElement^ obj, ::Platform::Object^ value, ::Platform::String^ targetNullValue)
    {
        if (value == nullptr && targetNullValue != nullptr)
        {
            value = (::Platform::Object^) ::Windows::UI::Xaml::Markup::XamlBindingHelper::ConvertValue(::Platform::Object::typeid, targetNullValue);
        }
        obj->Tag = value;
    }
    static void Set_Windows_UI_Xaml_Controls_TextBlock_Text(::Windows::UI::Xaml::Controls::TextBlock^ obj, ::Platform::String^ value, ::Platform::String^ targetNullValue)
    {
        if (value == nullptr && targetNullValue != nullptr)
        {
            value = targetNullValue;
        }
        obj->Text = value;
    }
};

/// <summary>
/// Auto generated class for compiled bindings.
/// </summary>
class CheckoutManager::DeviceViewPage::DeviceViewPage_obj9_Bindings 
    : public ::XamlBindingInfo::ReferenceTypeXamlBindings<::CheckoutManager::devicesGroup, ::XamlBindingInfo::XamlBindingTrackingBase>
{
public:
    DeviceViewPage_obj9_Bindings()
    {
    }

    void Connect(int __connectionId, ::Platform::Object^ __target)
    {
        switch(__connectionId)
        {
            case 9: // DeviceViewPage.xaml line 85
                this->obj9 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
                break;
            case 10: // DeviceViewPage.xaml line 88
                this->obj10 = safe_cast<::Windows::UI::Xaml::Controls::MenuFlyoutItem^>(__target);
                break;
        }
    }

    void DisconnectUnloadedObject(int connectionId)
    {
        throw ref new ::Platform::InvalidArgumentException("No unloadable elements to disconnect.");
    }

    void Recycle()
    {
    }

    void ProcessBindings(::Platform::Object^ item, int itemIndex, int phase, int* nextPhase)
    {
        switch (phase)
        {
            case 0:
                *nextPhase = -1;
                this->SetDataRoot(static_cast<::CheckoutManager::devicesGroup^>(item));
                if (this->_dataContextChangedToken.Value != 0)
                {
                    this->obj9.Resolve<::Windows::UI::Xaml::Controls::TextBlock>()->DataContextChanged -= this->_dataContextChangedToken;
                    this->_dataContextChangedToken.Value = 0;
                }
                this->_isInitialized = true;
                break;
            default:
                *nextPhase = -1;
                break;
        }
        this->Update_((::CheckoutManager::devicesGroup^) item, 1 << phase);
    }

private:
    // Fields for each control that has bindings.
    ::Platform::WeakReference obj9;
    ::Windows::UI::Xaml::Controls::MenuFlyoutItem^ obj10;

    // Update methods for each path node used in binding steps.
    void Update_(::CheckoutManager::devicesGroup^ obj, int phase)
    {
        if (obj != nullptr)
        {
            if ((phase & (NOT_PHASED | (1 << 0))) != 0)
            {
                this->Update_key(obj->key, phase);
                this->Update_color(obj->color, phase);
                this->Update_deleteGroup(obj->deleteGroup, phase);
            }
        }
    }
    void Update_key(::Platform::String^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // DeviceViewPage.xaml line 85
            if (this->obj9 != nullptr)
            {
                Set_Windows_UI_Xaml_Controls_TextBlock_Text(this->obj9.Resolve<::Windows::UI::Xaml::Controls::TextBlock>(), obj, nullptr);
            }
        }
    }
    void Update_color(::Windows::UI::Xaml::Media::SolidColorBrush^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // DeviceViewPage.xaml line 85
            if (this->obj9 != nullptr)
            {
                Set_Windows_UI_Xaml_Controls_TextBlock_Foreground(this->obj9.Resolve<::Windows::UI::Xaml::Controls::TextBlock>(), obj, nullptr);
            }
        }
    }
    void Update_deleteGroup(::Windows::UI::Xaml::Input::ICommand^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // DeviceViewPage.xaml line 88
            Set_Windows_UI_Xaml_Controls_MenuFlyoutItem_Command(this->obj10, obj, nullptr);
        }
    }
    static void Set_Windows_UI_Xaml_Controls_TextBlock_Text(::Windows::UI::Xaml::Controls::TextBlock^ obj, ::Platform::String^ value, ::Platform::String^ targetNullValue)
    {
        if (value == nullptr && targetNullValue != nullptr)
        {
            value = targetNullValue;
        }
        obj->Text = value;
    }
    static void Set_Windows_UI_Xaml_Controls_TextBlock_Foreground(::Windows::UI::Xaml::Controls::TextBlock^ obj, ::Windows::UI::Xaml::Media::Brush^ value, ::Platform::String^ targetNullValue)
    {
        if (value == nullptr && targetNullValue != nullptr)
        {
            value = (::Windows::UI::Xaml::Media::Brush^) ::Windows::UI::Xaml::Markup::XamlBindingHelper::ConvertValue(::Windows::UI::Xaml::Media::Brush::typeid, targetNullValue);
        }
        obj->Foreground = value;
    }
    static void Set_Windows_UI_Xaml_Controls_MenuFlyoutItem_Command(::Windows::UI::Xaml::Controls::MenuFlyoutItem^ obj, ::Windows::UI::Xaml::Input::ICommand^ value, ::Platform::String^ targetNullValue)
    {
        if (value == nullptr && targetNullValue != nullptr)
        {
            value = (::Windows::UI::Xaml::Input::ICommand^) ::Windows::UI::Xaml::Markup::XamlBindingHelper::ConvertValue(::Windows::UI::Xaml::Input::ICommand::typeid, targetNullValue);
        }
        obj->Command = value;
    }
};

/// <summary>
/// Auto generated class for compiled bindings.
/// </summary>
class CheckoutManager::DeviceViewPage::DeviceViewPage_obj1_Bindings 
    : public ::XamlBindingInfo::ReferenceTypeXamlBindings<::CheckoutManager::DeviceViewPage, ::XamlBindingInfo::XamlBindingTrackingBase>
{
public:
    DeviceViewPage_obj1_Bindings()
    {
    }

    void Connect(int __connectionId, ::Platform::Object^ __target)
    {
        switch(__connectionId)
        {
            case 2: // DeviceViewPage.xaml line 12
                this->obj2 = safe_cast<::Windows::UI::Xaml::Data::CollectionViewSource^>(__target);
                break;
            case 8: // DeviceViewPage.xaml line 74
                this->obj8 = safe_cast<::Windows::UI::Xaml::Controls::ListView^>(__target);
                break;
            case 15: // DeviceViewPage.xaml line 52
                this->obj15 = safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(__target);
                break;
        }
    }

    void DisconnectUnloadedObject(int connectionId)
    {
        throw ref new ::Platform::InvalidArgumentException("No unloadable elements to disconnect.");
    }

private:
    // Fields for each control that has bindings.
    ::Windows::UI::Xaml::Data::CollectionViewSource^ obj2;
    ::Windows::UI::Xaml::Controls::ListView^ obj8;
    ::Windows::UI::Xaml::Controls::ComboBox^ obj15;

    // Update methods for each path node used in binding steps.
    void Update_(::CheckoutManager::DeviceViewPage^ obj, int phase)
    {
        if (obj != nullptr)
        {
            if ((phase & (NOT_PHASED | (1 << 0))) != 0)
            {
                this->Update_bindDevices(obj->bindDevices, phase);
                this->Update_devicesGrouped(obj->devicesGrouped, phase);
            }
        }
    }
    void Update_bindDevices(::Windows::Foundation::Collections::IVector<::CheckoutManager::devicesGroup^>^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // DeviceViewPage.xaml line 12
            Set_Windows_UI_Xaml_Data_CollectionViewSource_Source(this->obj2, obj, nullptr);
            // DeviceViewPage.xaml line 52
            Set_Windows_UI_Xaml_Controls_ItemsControl_ItemsSource(this->obj15, obj, nullptr);
        }
    }
    void Update_devicesGrouped(::Windows::UI::Xaml::Data::CollectionViewSource^ obj, int phase)
    {
        if (obj != nullptr)
        {
            if ((phase & (NOT_PHASED | (1 << 0))) != 0)
            {
                this->Update_devicesGrouped_View(obj->View, phase);
            }
        }
    }
    void Update_devicesGrouped_View(::Windows::UI::Xaml::Data::ICollectionView^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // DeviceViewPage.xaml line 74
            Set_Windows_UI_Xaml_Controls_ItemsControl_ItemsSource(this->obj8, obj, nullptr);
        }
    }
    static void Set_Windows_UI_Xaml_Data_CollectionViewSource_Source(::Windows::UI::Xaml::Data::CollectionViewSource^ obj, ::Platform::Object^ value, ::Platform::String^ targetNullValue)
    {
        if (value == nullptr && targetNullValue != nullptr)
        {
            value = (::Platform::Object^) ::Windows::UI::Xaml::Markup::XamlBindingHelper::ConvertValue(::Platform::Object::typeid, targetNullValue);
        }
        obj->Source = value;
    }
    static void Set_Windows_UI_Xaml_Controls_ItemsControl_ItemsSource(::Windows::UI::Xaml::Controls::ItemsControl^ obj, ::Platform::Object^ value, ::Platform::String^ targetNullValue)
    {
        if (value == nullptr && targetNullValue != nullptr)
        {
            value = (::Platform::Object^) ::Windows::UI::Xaml::Markup::XamlBindingHelper::ConvertValue(::Platform::Object::typeid, targetNullValue);
        }
        obj->ItemsSource = value;
    }
};

void ::CheckoutManager::DeviceViewPage::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
    case 2:
        {
            this->devicesGrouped = safe_cast<::Windows::UI::Xaml::Data::CollectionViewSource^>(__target);
        }
        break;
    case 4:
        {
            ::Windows::UI::Xaml::Controls::MenuFlyoutItem^ element4 = safe_cast<::Windows::UI::Xaml::Controls::MenuFlyoutItem^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::MenuFlyoutItem^>(element4))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::CheckoutManager::DeviceViewPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&DeviceViewPage::MenuFlyoutItem_Click_1);
        }
        break;
    case 10:
        {
            ::Windows::UI::Xaml::Controls::MenuFlyoutItem^ element10 = safe_cast<::Windows::UI::Xaml::Controls::MenuFlyoutItem^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::MenuFlyoutItem^>(element10))->Loaded += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::CheckoutManager::DeviceViewPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&DeviceViewPage::MenuFlyoutItem_Loaded);
        }
        break;
    case 11:
        {
            this->typeTextbox = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
        }
        break;
    case 12:
        {
            ::Windows::UI::Xaml::Controls::Button^ element12 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(element12))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::CheckoutManager::DeviceViewPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&DeviceViewPage::AddDeviceType_Click);
        }
        break;
    case 13:
        {
            this->addDeviceTypeError = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(__target);
        }
        break;
    case 14:
        {
            this->addDeviceTypeWarning = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 15:
        {
            this->DeviceSelector = safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(__target);
        }
        break;
    case 16:
        {
            this->newdevdesc = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
        }
        break;
    case 17:
        {
            this->addDevicebutton = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->addDevicebutton))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::CheckoutManager::DeviceViewPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&DeviceViewPage::addDevicebutton_Click);
        }
        break;
    case 18:
        {
            this->addDeviceError = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(__target);
        }
        break;
    case 19:
        {
            this->addDeviceWarning = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::CheckoutManager::DeviceViewPage::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    ::XamlBindingInfo::XamlBindings^ bindings = nullptr;
    switch (__connectionId)
    {
        case 1: // DeviceViewPage.xaml line 1
            {
                ::Windows::UI::Xaml::Controls::Page^ element1 = safe_cast<::Windows::UI::Xaml::Controls::Page^>(__target);
                DeviceViewPage_obj1_Bindings* objBindings = new DeviceViewPage_obj1_Bindings();
                objBindings->SetDataRoot(this);
                bindings = ref new ::XamlBindingInfo::XamlBindings(objBindings);
                this->Bindings = bindings;
                element1->Loading += ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::FrameworkElement^, ::Platform::Object^>(bindings, &::XamlBindingInfo::XamlBindings::Loading);
            }
            break;
        case 3: // DeviceViewPage.xaml line 18
            {
                ::Windows::UI::Xaml::Controls::Grid^ element3 = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
                DeviceViewPage_obj3_Bindings* objBindings = new DeviceViewPage_obj3_Bindings();
                objBindings->SetDataRoot(element3->DataContext);
                objBindings->SetConverterLookupRoot(this);
                bindings = ref new ::XamlBindingInfo::XamlBindings(objBindings);
                bindings->SubscribeForDataContextChanged(element3);
                ::Windows::UI::Xaml::DataTemplate::SetExtensionInstance(element3, bindings);
                ::Windows::UI::Xaml::Markup::XamlBindingHelper::SetDataTemplateComponent(element3, bindings);
            }
            break;
        case 9: // DeviceViewPage.xaml line 85
            {
                ::Windows::UI::Xaml::Controls::TextBlock^ element9 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
                DeviceViewPage_obj9_Bindings* objBindings = new DeviceViewPage_obj9_Bindings();
                objBindings->SetDataRoot(element9->DataContext);
                bindings = ref new ::XamlBindingInfo::XamlBindings(objBindings);
                bindings->SubscribeForDataContextChanged(element9);
                ::Windows::UI::Xaml::DataTemplate::SetExtensionInstance(element9, bindings);
                ::Windows::UI::Xaml::Markup::XamlBindingHelper::SetDataTemplateComponent(element9, bindings);
            }
            break;
    }
    return bindings;
}

#pragma warning(pop)


