#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

#include "XamlBindingInfo.g.h"

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Data {
                ref class CollectionViewSource;
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class TextBox;
                ref class StackPanel;
                ref class TextBlock;
                ref class ComboBox;
                ref class Button;
            }
        }
    }
}

namespace CheckoutManager
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class DeviceViewPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        void UnloadObject(::Windows::UI::Xaml::DependencyObject^ dependencyObject);
        void DisconnectUnloadedObject(int connectionId);
    
    private:
        bool _contentLoaded;
    
        class DeviceViewPage_obj3_Bindings;
        class DeviceViewPage_obj8_Bindings;
        class DeviceViewPage_obj1_Bindings;
    
        ::XamlBindingInfo::XamlBindings^ Bindings;
        private: ::Windows::UI::Xaml::Data::CollectionViewSource^ devicesGrouped;
        private: ::Windows::UI::Xaml::Controls::TextBox^ typeTextbox;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ addDeviceTypeError;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ addDeviceTypeWarning;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ DeviceSelector;
        private: ::Windows::UI::Xaml::Controls::TextBox^ newdevdesc;
        private: ::Windows::UI::Xaml::Controls::Button^ addDevicebutton;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ addDeviceError;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ addDeviceWarning;
    };
}

