//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#pragma warning(push)
#pragma warning(disable: 4100) // unreferenced formal parameter

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "WeekEvent.xaml.h"

void ::CheckoutManager::WeekEvent::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///WeekEvent.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}


/// <summary>
/// Auto generated class for compiled bindings.
/// </summary>
class CheckoutManager::WeekEvent::WeekEvent_obj1_Bindings 
    : public ::XamlBindingInfo::ReferenceTypeXamlBindings<::CheckoutManager::WeekEvent, ::XamlBindingInfo::XamlBindingTrackingBase>
{
public:
    WeekEvent_obj1_Bindings()
    {
    }

    void Connect(int __connectionId, ::Platform::Object^ __target)
    {
        switch(__connectionId)
        {
            case 2: // WeekEvent.xaml line 15
                this->obj2 = safe_cast<::Windows::UI::Xaml::Documents::Run^>(__target);
                break;
            case 3: // WeekEvent.xaml line 18
                this->obj3 = safe_cast<::Windows::UI::Xaml::Documents::Run^>(__target);
                break;
            case 4: // WeekEvent.xaml line 21
                this->obj4 = safe_cast<::Windows::UI::Xaml::Documents::Run^>(__target);
                break;
            case 5: // WeekEvent.xaml line 24
                this->obj5 = safe_cast<::Windows::UI::Xaml::Documents::Run^>(__target);
                break;
            case 6: // WeekEvent.xaml line 27
                this->obj6 = safe_cast<::Windows::UI::Xaml::Documents::Run^>(__target);
                break;
            case 13: // WeekEvent.xaml line 50
                this->obj13 = safe_cast<::Windows::UI::Xaml::Controls::RelativePanel^>(__target);
                break;
            case 14: // WeekEvent.xaml line 51
                this->obj14 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
                break;
            case 17: // WeekEvent.xaml line 60
                this->obj17 = safe_cast<::Windows::UI::Xaml::Controls::Border^>(__target);
                break;
            case 18: // WeekEvent.xaml line 68
                this->obj18 = safe_cast<::Windows::UI::Xaml::Documents::Run^>(__target);
                break;
            case 19: // WeekEvent.xaml line 64
                this->obj19 = safe_cast<::Windows::UI::Xaml::Documents::Run^>(__target);
                break;
            case 20: // WeekEvent.xaml line 58
                this->obj20 = safe_cast<::Windows::UI::Xaml::Documents::Run^>(__target);
                break;
            case 21: // WeekEvent.xaml line 54
                this->obj21 = safe_cast<::Windows::UI::Xaml::Documents::Run^>(__target);
                break;
        }
    }

    void DisconnectUnloadedObject(int connectionId)
    {
        throw ref new ::Platform::InvalidArgumentException("No unloadable elements to disconnect.");
    }

private:
    // Fields for each control that has bindings.
    ::Windows::UI::Xaml::Documents::Run^ obj2;
    ::Windows::UI::Xaml::Documents::Run^ obj3;
    ::Windows::UI::Xaml::Documents::Run^ obj4;
    ::Windows::UI::Xaml::Documents::Run^ obj5;
    ::Windows::UI::Xaml::Documents::Run^ obj6;
    ::Windows::UI::Xaml::Controls::RelativePanel^ obj13;
    ::Windows::UI::Xaml::Controls::TextBlock^ obj14;
    ::Windows::UI::Xaml::Controls::Border^ obj17;
    ::Windows::UI::Xaml::Documents::Run^ obj18;
    ::Windows::UI::Xaml::Documents::Run^ obj19;
    ::Windows::UI::Xaml::Documents::Run^ obj20;
    ::Windows::UI::Xaml::Documents::Run^ obj21;

    // Update methods for each path node used in binding steps.
    void Update_(::CheckoutManager::WeekEvent^ obj, int phase)
    {
        if (obj != nullptr)
        {
            if ((phase & (NOT_PHASED | (1 << 0))) != 0)
            {
                this->Update_timeStr(obj->timeStr, phase);
                this->Update_deviceStr(obj->deviceStr, phase);
                this->Update_teamStr(obj->teamStr, phase);
                this->Update_actChecktime(obj->actChecktime, phase);
                this->Update_actReturntime(obj->actReturntime, phase);
                this->Update_background(obj->background, phase);
                this->Update_chk(obj->chk, phase);
            }
        }
    }
    void Update_timeStr(::Platform::String^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // WeekEvent.xaml line 15
            Set_Windows_UI_Xaml_Documents_Run_Text(this->obj2, obj, nullptr);
            // WeekEvent.xaml line 51
            Set_Windows_UI_Xaml_Controls_TextBlock_Text(this->obj14, obj, nullptr);
        }
    }
    void Update_deviceStr(::Platform::String^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // WeekEvent.xaml line 18
            Set_Windows_UI_Xaml_Documents_Run_Text(this->obj3, obj, nullptr);
            // WeekEvent.xaml line 54
            Set_Windows_UI_Xaml_Documents_Run_Text(this->obj21, obj, nullptr);
        }
    }
    void Update_teamStr(::Platform::String^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // WeekEvent.xaml line 21
            Set_Windows_UI_Xaml_Documents_Run_Text(this->obj4, obj, nullptr);
            // WeekEvent.xaml line 58
            Set_Windows_UI_Xaml_Documents_Run_Text(this->obj20, obj, nullptr);
        }
    }
    void Update_actChecktime(::Platform::String^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // WeekEvent.xaml line 24
            Set_Windows_UI_Xaml_Documents_Run_Text(this->obj5, obj, nullptr);
            // WeekEvent.xaml line 64
            Set_Windows_UI_Xaml_Documents_Run_Text(this->obj19, obj, nullptr);
        }
    }
    void Update_actReturntime(::Platform::String^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // WeekEvent.xaml line 27
            Set_Windows_UI_Xaml_Documents_Run_Text(this->obj6, obj, nullptr);
            // WeekEvent.xaml line 68
            Set_Windows_UI_Xaml_Documents_Run_Text(this->obj18, obj, nullptr);
        }
    }
    void Update_background(::Windows::UI::Xaml::Media::SolidColorBrush^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // WeekEvent.xaml line 50
            Set_Windows_UI_Xaml_Controls_Panel_Background(this->obj13, obj, nullptr);
        }
    }
    void Update_chk(::Platform::Boolean obj, int phase)
    {
            if ((phase & (NOT_PHASED | (1 << 0))) != 0)
            {
                this->Update_chk_Cast_chk_To_Visibility(obj ? ::Windows::UI::Xaml::Visibility::Visible : ::Windows::UI::Xaml::Visibility::Collapsed, phase);
            }
    }
    void Update_chk_Cast_chk_To_Visibility(::Windows::UI::Xaml::Visibility obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // WeekEvent.xaml line 60
            Set_Windows_UI_Xaml_UIElement_Visibility(this->obj17, obj);
        }
    }
    static void Set_Windows_UI_Xaml_Documents_Run_Text(::Windows::UI::Xaml::Documents::Run^ obj, ::Platform::String^ value, ::Platform::String^ targetNullValue)
    {
        if (value == nullptr && targetNullValue != nullptr)
        {
            value = targetNullValue;
        }
        obj->Text = value;
    }
    static void Set_Windows_UI_Xaml_Controls_Panel_Background(::Windows::UI::Xaml::Controls::Panel^ obj, ::Windows::UI::Xaml::Media::Brush^ value, ::Platform::String^ targetNullValue)
    {
        if (value == nullptr && targetNullValue != nullptr)
        {
            value = (::Windows::UI::Xaml::Media::Brush^) ::Windows::UI::Xaml::Markup::XamlBindingHelper::ConvertValue(::Windows::UI::Xaml::Media::Brush::typeid, targetNullValue);
        }
        obj->Background = value;
    }
    static void Set_Windows_UI_Xaml_Controls_TextBlock_Text(::Windows::UI::Xaml::Controls::TextBlock^ obj, ::Platform::String^ value, ::Platform::String^ targetNullValue)
    {
        if (value == nullptr && targetNullValue != nullptr)
        {
            value = targetNullValue;
        }
        obj->Text = value;
    }
    static void Set_Windows_UI_Xaml_UIElement_Visibility(::Windows::UI::Xaml::UIElement^ obj, ::Windows::UI::Xaml::Visibility value)
    {
        obj->Visibility = value;
    }
};

void ::CheckoutManager::WeekEvent::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
    case 1:
        {
            ::Windows::UI::Xaml::Controls::UserControl^ element1 = safe_cast<::Windows::UI::Xaml::Controls::UserControl^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::UserControl^>(element1))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::CheckoutManager::WeekEvent::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&WeekEvent::UserControl_Tapped);
        }
        break;
    case 7:
        {
            ::Windows::UI::Xaml::Controls::MenuFlyoutItem^ element7 = safe_cast<::Windows::UI::Xaml::Controls::MenuFlyoutItem^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::MenuFlyoutItem^>(element7))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::CheckoutManager::WeekEvent::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&WeekEvent::MenuFlyoutItem_Click);
        }
        break;
    case 8:
        {
            this->edit = safe_cast<::Windows::UI::Xaml::Controls::MenuFlyoutItem^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::MenuFlyoutItem^>(this->edit))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::CheckoutManager::WeekEvent::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&WeekEvent::edit_Click);
        }
        break;
    case 9:
        {
            ::Windows::UI::Xaml::Controls::MenuFlyoutItem^ element9 = safe_cast<::Windows::UI::Xaml::Controls::MenuFlyoutItem^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::MenuFlyoutItem^>(element9))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::CheckoutManager::WeekEvent::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&WeekEvent::MenuFlyoutItem_Click_1);
        }
        break;
    case 10:
        {
            this->DeviceID = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->DeviceID))->TextChanging += ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::Controls::TextBox^, ::Windows::UI::Xaml::Controls::TextBoxTextChangingEventArgs^>(this, (void (::CheckoutManager::WeekEvent::*)
                (::Windows::UI::Xaml::Controls::TextBox^, ::Windows::UI::Xaml::Controls::TextBoxTextChangingEventArgs^))&WeekEvent::DeviceID_TextChanging);
        }
        break;
    case 11:
        {
            this->Password = safe_cast<::Windows::UI::Xaml::Controls::PasswordBox^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::PasswordBox^>(this->Password))->PasswordChanged += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::CheckoutManager::WeekEvent::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&WeekEvent::Password_PasswordChanged);
        }
        break;
    case 12:
        {
            ::Windows::UI::Xaml::Controls::Button^ element12 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(element12))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::CheckoutManager::WeekEvent::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&WeekEvent::Button_Click);
        }
        break;
    case 13:
        {
            this->mainGrid = safe_cast<::Windows::UI::Xaml::Controls::RelativePanel^>(__target);
        }
        break;
    case 14:
        {
            this->timeblock = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 15:
        {
            this->itemblock = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 16:
        {
            this->Userblock = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 17:
        {
            this->fulfilledblock = safe_cast<::Windows::UI::Xaml::Controls::Border^>(__target);
        }
        break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::CheckoutManager::WeekEvent::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    ::XamlBindingInfo::XamlBindings^ bindings = nullptr;
    switch (__connectionId)
    {
        case 1: // WeekEvent.xaml line 1
            {
                ::Windows::UI::Xaml::Controls::UserControl^ element1 = safe_cast<::Windows::UI::Xaml::Controls::UserControl^>(__target);
                WeekEvent_obj1_Bindings* objBindings = new WeekEvent_obj1_Bindings();
                objBindings->SetDataRoot(this);
                bindings = ref new ::XamlBindingInfo::XamlBindings(objBindings);
                this->Bindings = bindings;
                element1->Loading += ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::FrameworkElement^, ::Platform::Object^>(bindings, &::XamlBindingInfo::XamlBindings::Loading);
            }
            break;
    }
    return bindings;
}

#pragma warning(pop)


