//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#pragma warning(push)
#pragma warning(disable: 4100) // unreferenced formal parameter

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "WeekEvent.xaml.h"

void ::CheckoutManager::WeekEvent::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///WeekEvent.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}


/// <summary>
/// Auto generated class for compiled bindings.
/// </summary>
class CheckoutManager::WeekEvent::WeekEvent_obj1_Bindings 
    : public ::XamlBindingInfo::ReferenceTypeXamlBindings<::CheckoutManager::WeekEvent>
{
public:
    WeekEvent_obj1_Bindings()
    {
    }

    void Connect(int __connectionId, ::Platform::Object^ __target)
    {
        switch(__connectionId)
        {
            case 8: // WeekEvent.xaml line 31
                this->obj8 = safe_cast<::Windows::UI::Xaml::Controls::RelativePanel^>(__target);
                break;
            case 9: // WeekEvent.xaml line 32
                this->obj9 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
                break;
            case 12: // WeekEvent.xaml line 40
                this->obj12 = safe_cast<::Windows::UI::Xaml::Documents::Run^>(__target);
                break;
            case 13: // WeekEvent.xaml line 36
                this->obj13 = safe_cast<::Windows::UI::Xaml::Documents::Run^>(__target);
                break;
        }
    }

    void DisconnectUnloadedObject(int connectionId)
    {
        throw ref new ::Platform::InvalidArgumentException("No unloadable elements to disconnect.");
    }
private:
    // Fields for each control that has bindings.
    ::Windows::UI::Xaml::Controls::RelativePanel^ obj8;
    ::Windows::UI::Xaml::Controls::TextBlock^ obj9;
    ::Windows::UI::Xaml::Documents::Run^ obj12;
    ::Windows::UI::Xaml::Documents::Run^ obj13;

    // Update methods for each path node used in binding steps.
    void Update_(::CheckoutManager::WeekEvent^ obj, int phase)
    {
        if (obj != nullptr)
        {
            if ((phase & (NOT_PHASED | (1 << 0))) != 0)
            {
                this->Update_background(obj->background, phase);
                this->Update_timeStr(obj->timeStr, phase);
                this->Update_teamStr(obj->teamStr, phase);
                this->Update_deviceStr(obj->deviceStr, phase);
            }
        }
    }
    void Update_background(::Windows::UI::Xaml::Media::SolidColorBrush^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // WeekEvent.xaml line 31
            ::XamlBindingInfo::XamlBindingSetters::Set_Windows_UI_Xaml_Controls_Panel_Background(this->obj8, obj, nullptr);
        }
    }
    void Update_timeStr(::Platform::String^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // WeekEvent.xaml line 32
            ::XamlBindingInfo::XamlBindingSetters::Set_Windows_UI_Xaml_Controls_TextBlock_Text(this->obj9, obj, nullptr);
        }
    }
    void Update_teamStr(::Platform::String^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // WeekEvent.xaml line 40
            ::XamlBindingInfo::XamlBindingSetters::Set_Windows_UI_Xaml_Documents_Run_Text(this->obj12, obj, nullptr);
        }
    }
    void Update_deviceStr(::Platform::String^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // WeekEvent.xaml line 36
            ::XamlBindingInfo::XamlBindingSetters::Set_Windows_UI_Xaml_Documents_Run_Text(this->obj13, obj, nullptr);
        }
    }
};

void ::CheckoutManager::WeekEvent::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
    case 1:
        {
            ::Windows::UI::Xaml::Controls::UserControl^ element1 = safe_cast<::Windows::UI::Xaml::Controls::UserControl^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::UserControl^>(element1))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::CheckoutManager::WeekEvent::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&WeekEvent::UserControl_Tapped);
        }
        break;
    case 2:
        {
            ::Windows::UI::Xaml::Controls::MenuFlyoutItem^ element2 = safe_cast<::Windows::UI::Xaml::Controls::MenuFlyoutItem^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::MenuFlyoutItem^>(element2))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::CheckoutManager::WeekEvent::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&WeekEvent::MenuFlyoutItem_Click);
        }
        break;
    case 3:
        {
            this->edit = safe_cast<::Windows::UI::Xaml::Controls::MenuFlyoutItem^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::MenuFlyoutItem^>(this->edit))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::CheckoutManager::WeekEvent::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&WeekEvent::edit_Click);
        }
        break;
    case 4:
        {
            ::Windows::UI::Xaml::Controls::MenuFlyoutItem^ element4 = safe_cast<::Windows::UI::Xaml::Controls::MenuFlyoutItem^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::MenuFlyoutItem^>(element4))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::CheckoutManager::WeekEvent::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&WeekEvent::MenuFlyoutItem_Click_1);
        }
        break;
    case 5:
        {
            this->DeviceID = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->DeviceID))->TextChanging += ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::Controls::TextBox^, ::Windows::UI::Xaml::Controls::TextBoxTextChangingEventArgs^>(this, (void (::CheckoutManager::WeekEvent::*)
                (::Windows::UI::Xaml::Controls::TextBox^, ::Windows::UI::Xaml::Controls::TextBoxTextChangingEventArgs^))&WeekEvent::DeviceID_TextChanging);
        }
        break;
    case 6:
        {
            this->Password = safe_cast<::Windows::UI::Xaml::Controls::PasswordBox^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::PasswordBox^>(this->Password))->PasswordChanged += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::CheckoutManager::WeekEvent::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&WeekEvent::Password_PasswordChanged);
        }
        break;
    case 7:
        {
            ::Windows::UI::Xaml::Controls::Button^ element7 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(element7))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::CheckoutManager::WeekEvent::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&WeekEvent::Button_Click);
        }
        break;
    case 8:
        {
            this->mainGrid = safe_cast<::Windows::UI::Xaml::Controls::RelativePanel^>(__target);
        }
        break;
    case 9:
        {
            this->timeblock = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 10:
        {
            this->check = safe_cast<::Windows::UI::Xaml::Controls::SymbolIcon^>(__target);
        }
        break;
    case 11:
        {
            this->itemblock = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::CheckoutManager::WeekEvent::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    ::XamlBindingInfo::XamlBindings^ bindings = nullptr;
    switch (__connectionId)
    {
        case 1: // WeekEvent.xaml line 1
            {
                ::Windows::UI::Xaml::Controls::UserControl^ element1 = safe_cast<::Windows::UI::Xaml::Controls::UserControl^>(__target);
                WeekEvent_obj1_Bindings* objBindings = new WeekEvent_obj1_Bindings();
                objBindings->SetDataRoot(this);
                bindings = ref new ::XamlBindingInfo::XamlBindings(objBindings);
                this->Bindings = bindings;
                element1->Loading += ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::FrameworkElement^, ::Platform::Object^>(bindings, &::XamlBindingInfo::XamlBindings::Loading);
            }
            break;
    }
    return bindings;
}

#pragma warning(pop)


