#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

#include "XamlBindingInfo.g.h"

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class MenuFlyoutItem;
                ref class TextBox;
                ref class PasswordBox;
                ref class RelativePanel;
                ref class TextBlock;
                ref class Border;
            }
        }
    }
}

namespace CheckoutManager
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class WeekEvent : public ::Windows::UI::Xaml::Controls::UserControl, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        void UnloadObject(::Windows::UI::Xaml::DependencyObject^ dependencyObject);
        void DisconnectUnloadedObject(int connectionId);
    
    private:
        bool _contentLoaded;
    
        class WeekEvent_obj1_Bindings;
    
        ::XamlBindingInfo::XamlBindings^ Bindings;
        private: ::Windows::UI::Xaml::Controls::MenuFlyoutItem^ edit;
        private: ::Windows::UI::Xaml::Controls::TextBox^ DeviceID;
        private: ::Windows::UI::Xaml::Controls::PasswordBox^ Password;
        private: ::Windows::UI::Xaml::Controls::RelativePanel^ mainGrid;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ timeblock;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ itemblock;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Userblock;
        private: ::Windows::UI::Xaml::Controls::Border^ fulfilledblock;
    };
}

