//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "pch.h"
#include "XamlTypeInfo.g.h"

#include "AddCheckout.xaml.h"
#include "AuthenticationDialog.xaml.h"
#include "Calpage.xaml.h"
#include "CheckoutPage.xaml.h"
#include "DeviceViewPage.xaml.h"
#include "LandingPage.xaml.h"
#include "OOBEPage.xaml.h"
#include "App.xaml.h"
#include "MainPage.xaml.h"
#include "TeamPage.xaml.h"
#include "TrialExpired.xaml.h"
#include "WeekEvent.xaml.h"
#include "WeekViewControl.xaml.h"
#include "XamlBindingInfo.g.hpp"
#include "AddCheckout.g.hpp"
#include "AuthenticationDialog.g.hpp"
#include "Calpage.g.hpp"
#include "CheckoutPage.g.hpp"
#include "DeviceViewPage.g.hpp"
#include "LandingPage.g.hpp"
#include "OOBEPage.g.hpp"
#include "App.g.hpp"
#include "MainPage.g.hpp"
#include "TeamPage.g.hpp"
#include "TrialExpired.g.hpp"
#include "WeekEvent.g.hpp"
#include "WeekViewControl.g.hpp"

template<typename T>
::Platform::Object^ ActivateType()
{
    return ref new T;
}

template<typename TInstance, typename TItem>
void CollectionAdd(::Platform::Object^ instance, ::Platform::Object^ item)
{
    safe_cast<TInstance^>(instance)->Append((TItem)item);
}

template<typename TInstance, typename TKey, typename TItem>
void DictionaryAdd(::Platform::Object^ instance, ::Platform::Object^ key, ::Platform::Object^ item)
{
    safe_cast<TInstance^>(instance)->Insert((TKey)key, (TItem)item);
}

template<typename T>
::Platform::Object^ FromStringConverter(::XamlTypeInfo::InfoProvider::XamlUserType^ userType, ::Platform::String^ input)
{
    return ref new ::Platform::Box<T>((T)userType->CreateEnumUIntFromString(input));
}

template<typename TDeclaringType, typename TValue>
::Platform::Object^ GetValueTypeMember_zoomed(::Platform::Object^ instance)
{
    return ref new ::Platform::Box<TValue>(safe_cast<TDeclaringType^>(instance)->zoomed);
}

template<typename TDeclaringType, typename TValue>
::Platform::Object^ GetValueTypeMember_chk(::Platform::Object^ instance)
{
    return ref new ::Platform::Box<TValue>(safe_cast<TDeclaringType^>(instance)->chk);
}

template<typename TDeclaringType, typename TValue>
::Platform::Object^ GetValueTypeMember_manuallyhidden(::Platform::Object^ instance)
{
    return ref new ::Platform::Box<TValue>(safe_cast<TDeclaringType^>(instance)->manuallyhidden);
}

template<typename TDeclaringType>
::Platform::Object^ GetReferenceTypeMember_cal(::Platform::Object^ instance)
{
    return safe_cast<TDeclaringType^>(instance)->cal;
}

template<typename TDeclaringType>
::Platform::Object^ GetReferenceTypeMember_dateRange(::Platform::Object^ instance)
{
    return safe_cast<TDeclaringType^>(instance)->dateRange;
}

template<typename TDeclaringType>
::Platform::Object^ GetReferenceTypeMember_CurrentCalendar(::Platform::Object^ instance)
{
    return safe_cast<TDeclaringType^>(instance)->CurrentCalendar;
}

template<typename TDeclaringType>
::Platform::Object^ GetReferenceTypeMember_bindDevices(::Platform::Object^ instance)
{
    return safe_cast<TDeclaringType^>(instance)->bindDevices;
}

template<typename TDeclaringType>
::Platform::Object^ GetReferenceTypeMember_devices(::Platform::Object^ instance)
{
    return safe_cast<TDeclaringType^>(instance)->devices;
}

template<typename TDeclaringType>
::Platform::Object^ GetReferenceTypeMember_deleteGroup(::Platform::Object^ instance)
{
    return safe_cast<TDeclaringType^>(instance)->deleteGroup;
}

template<typename TDeclaringType>
::Platform::Object^ GetReferenceTypeMember_key(::Platform::Object^ instance)
{
    return safe_cast<TDeclaringType^>(instance)->key;
}

template<typename TDeclaringType>
::Platform::Object^ GetReferenceTypeMember_color(::Platform::Object^ instance)
{
    return safe_cast<TDeclaringType^>(instance)->color;
}

template<typename TDeclaringType>
::Platform::Object^ GetReferenceTypeMember_numdevices(::Platform::Object^ instance)
{
    return safe_cast<TDeclaringType^>(instance)->numdevices;
}

template<typename TDeclaringType>
::Platform::Object^ GetReferenceTypeMember_dtf(::Platform::Object^ instance)
{
    return safe_cast<TDeclaringType^>(instance)->dtf;
}

template<typename TDeclaringType>
::Platform::Object^ GetReferenceTypeMember_datestr(::Platform::Object^ instance)
{
    return safe_cast<TDeclaringType^>(instance)->datestr;
}

template<typename TDeclaringType>
::Platform::Object^ GetReferenceTypeMember_AppFrame(::Platform::Object^ instance)
{
    return safe_cast<TDeclaringType^>(instance)->AppFrame;
}

template<typename TDeclaringType>
::Platform::Object^ GetReferenceTypeMember_bindTeams(::Platform::Object^ instance)
{
    return safe_cast<TDeclaringType^>(instance)->bindTeams;
}

template<typename TDeclaringType>
::Platform::Object^ GetReferenceTypeMember_teamName(::Platform::Object^ instance)
{
    return safe_cast<TDeclaringType^>(instance)->teamName;
}

template<typename TDeclaringType>
::Platform::Object^ GetReferenceTypeMember_background(::Platform::Object^ instance)
{
    return safe_cast<TDeclaringType^>(instance)->background;
}

template<typename TDeclaringType>
::Platform::Object^ GetReferenceTypeMember_actReturntime(::Platform::Object^ instance)
{
    return safe_cast<TDeclaringType^>(instance)->actReturntime;
}

template<typename TDeclaringType>
::Platform::Object^ GetReferenceTypeMember_actChecktime(::Platform::Object^ instance)
{
    return safe_cast<TDeclaringType^>(instance)->actChecktime;
}

template<typename TDeclaringType>
::Platform::Object^ GetReferenceTypeMember_timeStr(::Platform::Object^ instance)
{
    return safe_cast<TDeclaringType^>(instance)->timeStr;
}

template<typename TDeclaringType>
::Platform::Object^ GetReferenceTypeMember_deviceStr(::Platform::Object^ instance)
{
    return safe_cast<TDeclaringType^>(instance)->deviceStr;
}

template<typename TDeclaringType>
::Platform::Object^ GetReferenceTypeMember_teamStr(::Platform::Object^ instance)
{
    return safe_cast<TDeclaringType^>(instance)->teamStr;
}

template<typename TDeclaringType, typename TValue>
void SetValueTypeMember_zoomed(::Platform::Object^ instance, ::Platform::Object^ value)
{
    safe_cast<TDeclaringType^>(instance)->zoomed = safe_cast<::Platform::IBox<TValue>^>(value)->Value;
}

template<typename TDeclaringType, typename TValue>
void SetValueTypeMember_chk(::Platform::Object^ instance, ::Platform::Object^ value)
{
    safe_cast<TDeclaringType^>(instance)->chk = safe_cast<::Platform::IBox<TValue>^>(value)->Value;
}

template<typename TDeclaringType, typename TValue>
void SetValueTypeMember_manuallyhidden(::Platform::Object^ instance, ::Platform::Object^ value)
{
    safe_cast<TDeclaringType^>(instance)->manuallyhidden = safe_cast<::Platform::IBox<TValue>^>(value)->Value;
}

template<typename TDeclaringType, typename TValue>
void SetReferenceTypeMember_cal(::Platform::Object^ instance, ::Platform::Object^ value)
{
    safe_cast<TDeclaringType^>(instance)->cal = safe_cast<TValue^>(value);
}

template<typename TDeclaringType, typename TValue>
void SetReferenceTypeMember_devices(::Platform::Object^ instance, ::Platform::Object^ value)
{
    safe_cast<TDeclaringType^>(instance)->devices = safe_cast<TValue^>(value);
}

template<typename TDeclaringType, typename TValue>
void SetReferenceTypeMember_key(::Platform::Object^ instance, ::Platform::Object^ value)
{
    safe_cast<TDeclaringType^>(instance)->key = safe_cast<TValue^>(value);
}

template<typename TDeclaringType, typename TValue>
void SetReferenceTypeMember_color(::Platform::Object^ instance, ::Platform::Object^ value)
{
    safe_cast<TDeclaringType^>(instance)->color = safe_cast<TValue^>(value);
}

template<typename TDeclaringType, typename TValue>
void SetReferenceTypeMember_numdevices(::Platform::Object^ instance, ::Platform::Object^ value)
{
    safe_cast<TDeclaringType^>(instance)->numdevices = safe_cast<TValue^>(value);
}

template<typename TDeclaringType, typename TValue>
void SetReferenceTypeMember_teamName(::Platform::Object^ instance, ::Platform::Object^ value)
{
    safe_cast<TDeclaringType^>(instance)->teamName = safe_cast<TValue^>(value);
}

enum TypeInfo_Flags
{
    TypeInfo_Flags_None                 = 0x00,
    TypeInfo_Flags_IsLocalType          = 0x01,
    TypeInfo_Flags_IsSystemType         = 0x02,
    TypeInfo_Flags_IsReturnTypeStub     = 0x04,
    TypeInfo_Flags_IsBindable           = 0x08,
    TypeInfo_Flags_IsMarkupExtension    = 0x10, 
};

struct TypeInfo
{
    PCWSTR  typeName;
    PCWSTR contentPropertyName;
    ::Platform::Object^ (*activator)();
    void (*collectionAdd)(::Platform::Object^, ::Platform::Object^);
    void (*dictionaryAdd)(::Platform::Object^, ::Platform::Object^, ::Platform::Object^);
    ::Platform::Object^ (*fromStringConverter)(::XamlTypeInfo::InfoProvider::XamlUserType^, ::Platform::String^);
    int     baseTypeIndex;
    int     firstMemberIndex;
    int     firstEnumValueIndex;
    int     createFromStringIndex;
    ::Windows::UI::Xaml::Interop::TypeKind kindofType;
    unsigned int flags;
};

const TypeInfo TypeInfos[] = 
{
    //   0
    L"Object", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    0, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    //   1
    L"String", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    0, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    //   2
    L"Boolean", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    0, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    //   3
    L"System.ValueType", L"",
    nullptr, nullptr, nullptr, nullptr,
    0, // Object
    0, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_None,
    //   4
    L"CheckoutManager.Team", L"",
    &ActivateType<::CheckoutManager::Team>, nullptr, nullptr, nullptr,
    0, // Object
    0, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_None,
    //   5
    L"CheckoutManager.device", L"",
    nullptr, nullptr, nullptr, nullptr,
    3, // System.ValueType
    2, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_None,
    //   6
    L"CheckoutManager.CalInfo", L"",
    nullptr, nullptr, nullptr, nullptr,
    0, // Object
    2, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_IsReturnTypeStub | TypeInfo_Flags_None,
    //   7
    L"CheckoutManager.Calpage", L"",
    &ActivateType<::CheckoutManager::Calpage>, nullptr, nullptr, nullptr,
    18, // Windows.UI.Xaml.Controls.Page
    2, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_None,
    //   8
    L"CheckoutManager.MainPage", L"",
    &ActivateType<::CheckoutManager::MainPage>, nullptr, nullptr, nullptr,
    18, // Windows.UI.Xaml.Controls.Page
    3, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_None,
    //   9
    L"CheckoutManager.OOBEPage", L"",
    &ActivateType<::CheckoutManager::OOBEPage>, nullptr, nullptr, nullptr,
    18, // Windows.UI.Xaml.Controls.Page
    4, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_None,
    //  10
    L"CheckoutManager.TeamPage", L"",
    &ActivateType<::CheckoutManager::TeamPage>, nullptr, nullptr, nullptr,
    18, // Windows.UI.Xaml.Controls.Page
    4, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_None,
    //  11
    L"CheckoutManager.WeekEvent", L"",
    nullptr, nullptr, nullptr, nullptr,
    25, // Windows.UI.Xaml.Controls.UserControl
    5, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_None,
    //  12
    L"CheckoutManager.grouptostr", L"",
    &ActivateType<::CheckoutManager::grouptostr>, nullptr, nullptr, nullptr,
    0, // Object
    13, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_None,
    //  13
    L"CheckoutManager.AddCheckout", L"",
    &ActivateType<::CheckoutManager::AddCheckout>, nullptr, nullptr, nullptr,
    18, // Windows.UI.Xaml.Controls.Page
    13, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_None,
    //  14
    L"CheckoutManager.LandingPage", L"",
    &ActivateType<::CheckoutManager::LandingPage>, nullptr, nullptr, nullptr,
    18, // Windows.UI.Xaml.Controls.Page
    13, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_None,
    //  15
    L"CheckoutManager.CheckoutPage", L"",
    &ActivateType<::CheckoutManager::CheckoutPage>, nullptr, nullptr, nullptr,
    18, // Windows.UI.Xaml.Controls.Page
    16, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_None,
    //  16
    L"CheckoutManager.devicesGroup", L"",
    &ActivateType<::CheckoutManager::devicesGroup>, nullptr, nullptr, nullptr,
    0, // Object
    16, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_IsBindable | TypeInfo_Flags_None,
    //  17
    L"CheckoutManager.TrialExpired", L"",
    &ActivateType<::CheckoutManager::TrialExpired>, nullptr, nullptr, nullptr,
    18, // Windows.UI.Xaml.Controls.Page
    20, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_None,
    //  18
    L"Windows.UI.Xaml.Controls.Page", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    20, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    //  19
    L"CheckoutManager.DeviceViewPage", L"",
    &ActivateType<::CheckoutManager::DeviceViewPage>, nullptr, nullptr, nullptr,
    18, // Windows.UI.Xaml.Controls.Page
    20, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_None,
    //  20
    L"Windows.UI.Xaml.Input.ICommand", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    21, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    //  21
    L"Windows.UI.Xaml.Controls.Frame", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    21, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    //  22
    L"CheckoutManager.WeekViewControl", L"",
    &ActivateType<::CheckoutManager::WeekViewControl>, nullptr, nullptr, nullptr,
    25, // Windows.UI.Xaml.Controls.UserControl
    21, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_None,
    //  23
    L"CheckoutManager.MonthViewControl", L"",
    &ActivateType<::CheckoutManager::MonthViewControl>, nullptr, nullptr, nullptr,
    27, // Windows.UI.Xaml.Controls.CalendarView
    24, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_None,
    //  24
    L"Windows.UI.Xaml.DependencyObject", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    25, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    //  25
    L"Windows.UI.Xaml.Controls.UserControl", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    25, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    //  26
    L"CheckoutManager.AuthenticationDialog", L"",
    nullptr, nullptr, nullptr, nullptr,
    29, // Windows.UI.Xaml.Controls.ContentDialog
    25, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_None,
    //  27
    L"Windows.UI.Xaml.Controls.CalendarView", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    25, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    //  28
    L"Windows.UI.Xaml.Media.SolidColorBrush", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    25, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    //  29
    L"Windows.UI.Xaml.Controls.ContentDialog", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    25, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    //  30
    L"CheckoutManager.converters.booltocolor", L"",
    &ActivateType<::CheckoutManager::converters::booltocolor>, nullptr, nullptr, nullptr,
    24, // Windows.UI.Xaml.DependencyObject
    25, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_None,
    //  31
    L"Windows.UI.Xaml.Controls.ContentControl", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    25, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    //  32
    L"CheckoutManager.converters.booltosymbol", L"",
    &ActivateType<::CheckoutManager::converters::booltosymbol>, nullptr, nullptr, nullptr,
    0, // Object
    25, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_None,
    //  33
    L"CheckoutManager.converters.BooleanToVisibilityConverter", L"",
    &ActivateType<::CheckoutManager::converters::BooleanToVisibilityConverter>, nullptr, nullptr, nullptr,
    0, // Object
    25, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_None,
    //  34
    L"Windows.Foundation.Collections.IVector`1<CheckoutManager.Team>", L"",
    nullptr, &CollectionAdd<::Windows::Foundation::Collections::IVector<::CheckoutManager::Team^>, ::CheckoutManager::Team^>, nullptr, nullptr,
    -1,
    25, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsReturnTypeStub | TypeInfo_Flags_None,
    //  35
    L"Windows.Foundation.Collections.IVector`1<CheckoutManager.device>", L"",
    nullptr, &CollectionAdd<::Windows::Foundation::Collections::IVector<::CheckoutManager::device>, ::CheckoutManager::device>, nullptr, nullptr,
    -1,
    25, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsReturnTypeStub | TypeInfo_Flags_None,
    //  36
    L"Windows.Foundation.Collections.IVector`1<CheckoutManager.devicesGroup>", L"",
    nullptr, &CollectionAdd<::Windows::Foundation::Collections::IVector<::CheckoutManager::devicesGroup^>, ::CheckoutManager::devicesGroup^>, nullptr, nullptr,
    -1,
    25, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsReturnTypeStub | TypeInfo_Flags_None,
    //  Last type here is for padding
    L"", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1, 
    25, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    TypeInfo_Flags_None,
};

const UINT TypeInfoLookup[] = { 
      0,   //   0
      0,   //   1
      0,   //   2
      0,   //   3
      0,   //   4
      0,   //   5
      0,   //   6
      2,   //   7
      3,   //   8
      3,   //   9
      3,   //  10
      3,   //  11
      3,   //  12
      3,   //  13
      3,   //  14
      3,   //  15
      3,   //  16
      4,   //  17
      4,   //  18
      4,   //  19
      4,   //  20
      5,   //  21
      5,   //  22
      6,   //  23
      8,   //  24
     11,   //  25
     12,   //  26
     13,   //  27
     15,   //  28
     18,   //  29
     19,   //  30
     22,   //  31
     23,   //  32
     25,   //  33
     25,   //  34
     25,   //  35
     25,   //  36
     27,   //  37
     29,   //  38
     31,   //  39
     33,   //  40
     33,   //  41
     33,   //  42
     33,   //  43
     33,   //  44
     33,   //  45
     33,   //  46
     33,   //  47
     33,   //  48
     33,   //  49
     33,   //  50
     33,   //  51
     33,   //  52
     33,   //  53
     33,   //  54
     33,   //  55
     34,   //  56
     34,   //  57
     34,   //  58
     34,   //  59
     34,   //  60
     34,   //  61
     34,   //  62
     35,   //  63
     35,   //  64
     36,   //  65
     36,   //  66
     36,   //  67
     36,   //  68
     36,   //  69
     36,   //  70
     37,   //  71
};

struct MemberInfo 
{
    PCWSTR shortName;
    ::Platform::Object^ (*getter)(::Platform::Object^);
    void (*setter)(::Platform::Object^, ::Platform::Object^);
    int typeIndex;
    int targetTypeIndex;
    bool isReadOnly;
    bool isDependencyProperty;
    bool isAttachable;
};

const MemberInfo MemberInfos[] = 
{
    //   0 - CheckoutManager.Team.color
    L"color",
    &GetReferenceTypeMember_color<::CheckoutManager::Team>,
    &SetReferenceTypeMember_color<::CheckoutManager::Team, ::Windows::UI::Xaml::Media::SolidColorBrush>,
    28, // Windows.UI.Xaml.Media.SolidColorBrush
    -1,
    false, false, false,
    //   1 - CheckoutManager.Team.teamName
    L"teamName",
    &GetReferenceTypeMember_teamName<::CheckoutManager::Team>,
    &SetReferenceTypeMember_teamName<::CheckoutManager::Team, ::Platform::String>,
    1, // String
    -1,
    false, false, false,
    //   2 - CheckoutManager.Calpage.CurrentCalendar
    L"CurrentCalendar",
    &GetReferenceTypeMember_CurrentCalendar<::CheckoutManager::Calpage>,
    nullptr,
    6, // CheckoutManager.CalInfo
    -1,
    true,  false, false,
    //   3 - CheckoutManager.MainPage.AppFrame
    L"AppFrame",
    &GetReferenceTypeMember_AppFrame<::CheckoutManager::MainPage>,
    nullptr,
    21, // Windows.UI.Xaml.Controls.Frame
    -1,
    true,  false, false,
    //   4 - CheckoutManager.TeamPage.bindTeams
    L"bindTeams",
    &GetReferenceTypeMember_bindTeams<::CheckoutManager::TeamPage>,
    nullptr,
    34, // Windows.Foundation.Collections.IVector`1<CheckoutManager.Team>
    -1,
    true,  false, false,
    //   5 - CheckoutManager.WeekEvent.background
    L"background",
    &GetReferenceTypeMember_background<::CheckoutManager::WeekEvent>,
    nullptr,
    28, // Windows.UI.Xaml.Media.SolidColorBrush
    -1,
    true,  false, false,
    //   6 - CheckoutManager.WeekEvent.chk
    L"chk",
    &GetValueTypeMember_chk<::CheckoutManager::WeekEvent, ::Platform::Boolean>,
    &SetValueTypeMember_chk<::CheckoutManager::WeekEvent, ::Platform::Boolean>,
    2, // Boolean
    -1,
    false, false, false,
    //   7 - CheckoutManager.WeekEvent.actReturntime
    L"actReturntime",
    &GetReferenceTypeMember_actReturntime<::CheckoutManager::WeekEvent>,
    nullptr,
    1, // String
    -1,
    true,  false, false,
    //   8 - CheckoutManager.WeekEvent.actChecktime
    L"actChecktime",
    &GetReferenceTypeMember_actChecktime<::CheckoutManager::WeekEvent>,
    nullptr,
    1, // String
    -1,
    true,  false, false,
    //   9 - CheckoutManager.WeekEvent.timeStr
    L"timeStr",
    &GetReferenceTypeMember_timeStr<::CheckoutManager::WeekEvent>,
    nullptr,
    1, // String
    -1,
    true,  false, false,
    //  10 - CheckoutManager.WeekEvent.deviceStr
    L"deviceStr",
    &GetReferenceTypeMember_deviceStr<::CheckoutManager::WeekEvent>,
    nullptr,
    1, // String
    -1,
    true,  false, false,
    //  11 - CheckoutManager.WeekEvent.manuallyhidden
    L"manuallyhidden",
    &GetValueTypeMember_manuallyhidden<::CheckoutManager::WeekEvent, ::Platform::Boolean>,
    &SetValueTypeMember_manuallyhidden<::CheckoutManager::WeekEvent, ::Platform::Boolean>,
    2, // Boolean
    -1,
    false, false, false,
    //  12 - CheckoutManager.WeekEvent.teamStr
    L"teamStr",
    &GetReferenceTypeMember_teamStr<::CheckoutManager::WeekEvent>,
    nullptr,
    1, // String
    -1,
    true,  false, false,
    //  13 - CheckoutManager.LandingPage.numdevices
    L"numdevices",
    &GetReferenceTypeMember_numdevices<::CheckoutManager::LandingPage>,
    &SetReferenceTypeMember_numdevices<::CheckoutManager::LandingPage, ::Platform::String>,
    1, // String
    -1,
    false, false, false,
    //  14 - CheckoutManager.LandingPage.dtf
    L"dtf",
    &GetReferenceTypeMember_dtf<::CheckoutManager::LandingPage>,
    nullptr,
    1, // String
    -1,
    true,  false, false,
    //  15 - CheckoutManager.LandingPage.datestr
    L"datestr",
    &GetReferenceTypeMember_datestr<::CheckoutManager::LandingPage>,
    nullptr,
    1, // String
    -1,
    true,  false, false,
    //  16 - CheckoutManager.devicesGroup.devices
    L"devices",
    &GetReferenceTypeMember_devices<::CheckoutManager::devicesGroup>,
    &SetReferenceTypeMember_devices<::CheckoutManager::devicesGroup, ::Windows::Foundation::Collections::IVector<::CheckoutManager::device>>,
    35, // Windows.Foundation.Collections.IVector`1<CheckoutManager.device>
    -1,
    false, false, false,
    //  17 - CheckoutManager.devicesGroup.deleteGroup
    L"deleteGroup",
    &GetReferenceTypeMember_deleteGroup<::CheckoutManager::devicesGroup>,
    nullptr,
    20, // Windows.UI.Xaml.Input.ICommand
    -1,
    true,  false, false,
    //  18 - CheckoutManager.devicesGroup.key
    L"key",
    &GetReferenceTypeMember_key<::CheckoutManager::devicesGroup>,
    &SetReferenceTypeMember_key<::CheckoutManager::devicesGroup, ::Platform::String>,
    1, // String
    -1,
    false, false, false,
    //  19 - CheckoutManager.devicesGroup.color
    L"color",
    &GetReferenceTypeMember_color<::CheckoutManager::devicesGroup>,
    &SetReferenceTypeMember_color<::CheckoutManager::devicesGroup, ::Windows::UI::Xaml::Media::SolidColorBrush>,
    28, // Windows.UI.Xaml.Media.SolidColorBrush
    -1,
    false, false, false,
    //  20 - CheckoutManager.DeviceViewPage.bindDevices
    L"bindDevices",
    &GetReferenceTypeMember_bindDevices<::CheckoutManager::DeviceViewPage>,
    nullptr,
    36, // Windows.Foundation.Collections.IVector`1<CheckoutManager.devicesGroup>
    -1,
    true,  false, false,
    //  21 - CheckoutManager.WeekViewControl.cal
    L"cal",
    &GetReferenceTypeMember_cal<::CheckoutManager::WeekViewControl>,
    &SetReferenceTypeMember_cal<::CheckoutManager::WeekViewControl, ::CheckoutManager::CalInfo>,
    6, // CheckoutManager.CalInfo
    -1,
    false, false, false,
    //  22 - CheckoutManager.WeekViewControl.dateRange
    L"dateRange",
    &GetReferenceTypeMember_dateRange<::CheckoutManager::WeekViewControl>,
    nullptr,
    1, // String
    -1,
    true,  false, false,
    //  23 - CheckoutManager.WeekViewControl.zoomed
    L"zoomed",
    &GetValueTypeMember_zoomed<::CheckoutManager::WeekViewControl, ::Platform::Boolean>,
    &SetValueTypeMember_zoomed<::CheckoutManager::WeekViewControl, ::Platform::Boolean>,
    2, // Boolean
    -1,
    false, false, false,
    //  24 - CheckoutManager.MonthViewControl.cal
    L"cal",
    &GetReferenceTypeMember_cal<::CheckoutManager::MonthViewControl>,
    &SetReferenceTypeMember_cal<::CheckoutManager::MonthViewControl, ::CheckoutManager::CalInfo>,
    6, // CheckoutManager.CalInfo
    -1,
    false, false, false,
};

PCWSTR GetShortName(PCWSTR longName)
{
    PCWSTR separator = wcsrchr(longName, '.');
    return separator != nullptr ? separator + 1: longName;
}

const TypeInfo* GetTypeInfo(::Platform::String^ typeName)
{
    auto typeNameLength = typeName->Length();
    if (typeNameLength < _countof(TypeInfoLookup) - 1)
    {
        for (UINT i = TypeInfoLookup[typeNameLength]; i < TypeInfoLookup[typeNameLength+1]; i++)
        {
            if (typeName == ::Platform::StringReference(TypeInfos[i].typeName))
            {
                return &TypeInfos[i];
            }
        }
    }
    return nullptr;
}

const MemberInfo* GetMemberInfo(::Platform::String^ longMemberName)
{
    auto lastDotIndex = longMemberName->Length();
    while (true)
    {
        if (longMemberName->Data()[lastDotIndex] == '.')
        {
            const TypeInfo* pTypeInfo = GetTypeInfo(ref new ::Platform::String(longMemberName->Data(), lastDotIndex));
            const TypeInfo* pNextTypeInfo = pTypeInfo + 1;
            if (pTypeInfo)
            {
                PCWSTR shortMemberName = GetShortName(longMemberName->Data());
                for (int i = pTypeInfo->firstMemberIndex; i < pNextTypeInfo->firstMemberIndex; i++)
                {
                    if (wcscmp(shortMemberName, MemberInfos[i].shortName) == 0)
                    {
                        return &MemberInfos[i];
                    }
                }
            }
            break;
        }
        if (lastDotIndex == 0)
        {
            break;
        }
        lastDotIndex--;
    }
    return nullptr;
}

::Platform::Collections::Vector<::Windows::UI::Xaml::Markup::IXamlMetadataProvider^>^ ::XamlTypeInfo::InfoProvider::XamlTypeInfoProvider::OtherProviders::get()
{
    if(_otherProviders == nullptr)
    {
        auto otherProviders = ref new ::Platform::Collections::Vector<::Windows::UI::Xaml::Markup::IXamlMetadataProvider^>();
        _otherProviders = otherProviders;
    }
    return _otherProviders;
}

::Windows::UI::Xaml::Markup::IXamlType^ ::XamlTypeInfo::InfoProvider::XamlTypeInfoProvider::CreateXamlType(::Platform::String^ typeName)
{
    const TypeInfo* pTypeInfo = GetTypeInfo(typeName);
    const TypeInfo* pNextTypeInfo = pTypeInfo + 1;
    if (pTypeInfo == nullptr || pNextTypeInfo == nullptr)
    {
        return nullptr;
    }
    else if (pTypeInfo->flags & TypeInfo_Flags_IsSystemType)
    {
        return ref new ::XamlTypeInfo::InfoProvider::XamlSystemBaseType(typeName);
    }
    else
    {
        ::XamlTypeInfo::InfoProvider::XamlUserType^ userType = ref new ::XamlTypeInfo::InfoProvider::XamlUserType(
            this, 
            ::Platform::StringReference(pTypeInfo->typeName), 
            this->GetXamlTypeByName(::Platform::StringReference(pTypeInfo->baseTypeIndex >= 0 ? TypeInfos[pTypeInfo->baseTypeIndex].typeName : L"")));
        userType->KindOfType = pTypeInfo->kindofType;
        userType->Activator = pTypeInfo->activator;
        userType->CollectionAdd = pTypeInfo->collectionAdd;
        userType->DictionaryAdd = pTypeInfo->dictionaryAdd;
        userType->FromStringConverter = pTypeInfo->fromStringConverter;
        userType->ContentPropertyName = ::Platform::StringReference(pTypeInfo->contentPropertyName);
        userType->IsLocalType = pTypeInfo->flags & TypeInfo_Flags_IsLocalType;
        userType->IsReturnTypeStub = pTypeInfo->flags & TypeInfo_Flags_IsReturnTypeStub;
        userType->IsBindable = pTypeInfo->flags & TypeInfo_Flags_IsBindable;
        userType->IsMarkupExtension = pTypeInfo->flags & TypeInfo_Flags_IsMarkupExtension;
        userType->CreateFromStringMethod = nullptr;
        int nextMemberIndex = pTypeInfo->firstMemberIndex;
        for (int i=pTypeInfo->firstMemberIndex; i < pNextTypeInfo->firstMemberIndex; i++)
        {
            userType->AddMemberName(::Platform::StringReference(MemberInfos[i].shortName));
            nextMemberIndex++;
        }
        return userType;
    }
}

::Windows::UI::Xaml::Markup::IXamlMember^ ::XamlTypeInfo::InfoProvider::XamlTypeInfoProvider::CreateXamlMember(::Platform::String^ longMemberName)
{
    ::XamlTypeInfo::InfoProvider::XamlMember^ xamlMember = nullptr;
    const MemberInfo* pMemberInfo = GetMemberInfo(longMemberName);
    if (pMemberInfo != nullptr)
    {
        xamlMember = ref new ::XamlTypeInfo::InfoProvider::XamlMember(
            this,
            ::Platform::StringReference(pMemberInfo->shortName),
            ::Platform::StringReference(TypeInfos[pMemberInfo->typeIndex].typeName));
        xamlMember->Getter = pMemberInfo->getter;
        xamlMember->Setter = pMemberInfo->setter;
        xamlMember->TargetTypeName = pMemberInfo->targetTypeIndex >= 0 ? ::Platform::StringReference(TypeInfos[pMemberInfo->targetTypeIndex].typeName) : L"";
        xamlMember->IsReadOnly = pMemberInfo->isReadOnly;
        xamlMember->IsDependencyProperty = pMemberInfo->isDependencyProperty;
        xamlMember->IsAttachable = pMemberInfo->isAttachable;
    }
    return xamlMember;
}

